name: ci
on:
    push:
        branches: [develop]

jobs:
    lint:
        runs-on: [self-hosted, linux, x64]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: lint
              run: php -l *.php
    build:
        runs-on : self-hosted
        steps:
            - name : Checkout repo
              uses: actions/checkout@v3
            - name : Set up Docker Buildx
              uses : docker/setup-buildx-action@v2
            - name : Build Docker image
              run: |
                  docker build -t my-image-name:latest .
    push:
        runs-on : self-hosted
        steps :
            - name : log in to DockerHub
              uses : docker/login-action@v2
              with : 
                      username: ${{ secrets.DOCKERHUB_USERNAME }}
                      password: ${{ secrets.DOCKERHUB_PASSWORD }}
                      
            - name: Push Docker image
              run: |
                  docker tag my-image-name:latest your-dockerhub-username/my-image-name:latest
                  docker push your-dockerhub-username/my-image-name:latest
    
